### ISSUE TITLE
Using venom results in "App keeps stopping" dialog 

### ISSUE THREAD

**Issue by ColtonIdle** [YarikSOffice/venom#31]
I keep getting a "RollerToaster keeps stopping" dialog even though my app is closed. I also don't see venom in the notication tray. I believe I hit the "cancel" button in the notifaction tray.

Now like every minute or so I get this dialog, so I looked in logout. I have this same stacktrace over and over and over.

```
2022-01-26 22:46:51.785 17245-17245/com.rollertoaster.app.free E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rollertoaster.app.free, PID: 17245
    java.lang.RuntimeException: Unable to create application com.rollertoaster.app.MyApplication: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.rollertoaster.app.free/com.github.venom.service.VenomService
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6730)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.rollertoaster.app.free/com.github.venom.service.VenomService
        at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
        at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
        at android.os.Parcel.readParcelable(Parcel.java:3333)
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2420)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5971)
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1847)
        at android.app.ContextImpl.startForegroundService(ContextImpl.java:1823)
        at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:779)
        at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
        at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
        at com.github.venom.service.ServiceDelegate.startService(ServiceDelegate.kt:12)
        at com.github.venom.Venom.start(Venom.kt:61)
        at com.github.venom.Venom.initialize(Venom.kt:52)
        at com.github.venom.Venom.initialize$default(Venom.kt:49)
        at com.github.venom.Venom.initialize(Unknown Source:2)
        at com.rollertoaster.app.MyApplication.onCreate(MyApplication.java:388)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:691)
        at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:616)
        at com.android.server.am.ActivityManagerService.startService(ActivityManagerService.java:11850)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2519)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2498)
        ```

Can we do anything about it?

**Comment by YarikSOffice** [comment]
Apps that target Android 12 (API level 31) or higher can't start foreground services while running in the background, except for [a few special cases](https://developer.android.com/guide/components/foreground-services#background-start-restriction-exemptions). If an app tries to start a foreground service while the app is running in the background, and the foreground service doesn't satisfy one of the exceptional cases, the system throws a ForegroundServiceStartNotAllowedException. 

Please refer to this [link](https://developer.android.com/guide/components/foreground-services#background-start-restrictions).

Therefore, you have to make sure your app is in the foreground when enabling the Venom service.

**Comment by ColtonIdle** [comment]
So the sample is outdated I suppose?
https://github.com/YarikSOffice/venom/blob/master/sample/src/main/java/com/github/venom/sample/App.kt

**Comment by YarikSOffice** [comment]
Not really, the sample should not be outdated. The only concern is an edge case that I'm not aware of.

I've just tested the sample app on Android 12 and it seems to work as expected. The app should be considered "foreground" when onCreate is called.

**Comment by ColtonIdle** [comment]
Alright. This is over my head I suppose. I'm not really sure what's going on except for the fact that my app is setup like the sample. But then once the app is backgrounded, I hit the cancel button on the notification and then I get an exception. If this is user error, then feel free to close. thanks for your time

**Comment by YarikSOffice** [comment]
I've just made more tests in another app, everything seems to work fine.

Please, reopen the ticket if you find the reason behind this. Thanks!
